spring.application.name=productosApi

server.port = 8080

#Activar consola h2
spring.h2.console.enabled = true

#Ruta H2
spring.h2.console.path=/h2-console

#URL Base de datos
spring.datasource.url=jdbc:h2:mem:productosdb

#Driver H2
spring.datasource.driver-class-name=org.h2.Driver

#Datos de conexión
spring.datasource.username =sa
spring.datasource.password =

#cuando yo ejecute la app tu automaticamente creame la db y la tabla
spring.jpa.hibernate.ddl-auto=create-drop

#Mostrar SQL EN CONSOLA
spring.jpa.show-sql = true